export const SET_LOADING = "SET_LOADING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const FETCH_CATEGORY_PERFORMANCES_SUCCESS = 'FETCH_CATEGORY_PERFORMANCES_SUCCESS';
export const FETCH_CATEGORY_PERFORMANCES_ERROR = 'FETCH_CATEGORY_PERFORMANCES_ERROR';
