/**
 * File to store potential actions for our Categories
 */
export const CREATE_CATEGORIES_SUCCESS = "CREATE_CATEGORIES_SUCCESS";
export const CREATE_CATEGORIES_FAIL = "CREATE_CATEGORIES_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_LOADING = "SET_LOADING";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";
export const UPDATE_CATEGORY_ALLOCATIONS_SUCCESS =
   "UPDATE_CATEGORY_ALLOCATIONS_SUCCESS";
export const UPDATE_CATEGORY_ALLOCATIONS_FAIL =
   "UPDATE_CATEGORY_ALLOCATIONS_FAIL";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const RENAME_CATEGORY_SUCCESS = "RENAME_CATEGORY_SUCCESS";
export const RENAME_CATEGORY_FAIL = "RENAME_CATEGORY_FAIL";
