pipeline {
    agent any

    tools {
        gradle 'gradle8.3'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scmGit(branches: [[name: '*/feat/MoveFromGCloudToSelfHosting']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/KBavis/budgeting-app']])
            }
        }

        stage('Extract Version') {
            steps {
                script {
                    def props = readProperties file: 'backend/gradle.properties'
                    def baseVersion = props['projectVersion']
                    def buildNumber = env.BUILD_NUMBER
                    env.BASE_VERSION = "${baseVersion}"
                    env.VERSION = "${baseVersion}.${buildNumber}"
                    echo "Version: ${env.VERSION}"
                }
            }
        }

        stage('Copy Config Files') {
            steps {
                dir('backend/src/resources/') {
                    bat 'copy "D:\\Code\\Workplace\\BudgetApp\\budgeting-app\\backend\\src\\resources\\application.yaml" .'
                    bat 'copy "D:\\Code\\Workplace\\BudgetApp\\budgeting-app\\backend\\src\\resources\\.env" .'
                    bat 'copy "D:\\Code\\Workplace\\BudgetApp\\budgeting-app\\backend\\src\\resources\\application-test.yaml" .'
                }
            }
        }

        stage('Build Gradle') {
            steps {
                dir('backend') {
                    bat 'gradle clean build'
                }
            }
        }

        stage('Build Backend Docker Image') {
            steps {
                dir('backend') {
                    script {
                        def imageVersion = env.VERSION
                        def baseVersion = env.BASE_VERSION
                        bat "docker build -t budget-app-backend:${imageVersion} --build-arg VERSION=${baseVersion} -f docker/Dockerfile ."
                    }
                }
            }
        }


        stage('Push Backend Docker Image to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'dockerhubpwd')]) {
                    script {
                        def version = env.VERSION
                        def dockerImage = "budget-app-backend:${version}"
                        def dockerHubImage = "baviske/budget-app-backend:${version}"

                        bat "docker login -u baviske -p ${dockerhubpwd} docker.io"
                        bat "docker tag ${dockerImage} ${dockerHubImage}"
                        bat "docker push ${dockerHubImage}"
                    }
                }
            }
        }

        stage('Deploy To Server') {
            steps {
                script {
                    withCredentials([
                        string(credentialsId: 'server-ip', variable: 'SERVER_IP'),
                        sshUserPrivateKey(credentialsId: 'deploy-ssh-key', keyFileVariable: 'SSH_KEY', usernameVariable: 'SSH_USER')
                    ]) {
                        bat '''
                            REM fix ssh key permssions (jenkins running on windows service account issue)
                            powershell -Command "$acl = Get-Acl '%SSH_KEY%'; $acl.SetAccessRuleProtection($true, $false); $acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) }; $rule = New-Object System.Security.AccessControl.FileSystemAccessRule('NT AUTHORITY\\SYSTEM', 'FullControl', 'Allow'); $acl.SetAccessRule($rule); Set-Acl '%SSH_KEY%' $acl"

                            REM copy latest application configs
                            scp -i "%SSH_KEY%" -o StrictHostKeyChecking=no compose.yaml %SSH_USER%@%SERVER_IP%:/home/deployuser

                            REM ssh to update version and restart containers
                            ssh -i "%SSH_KEY%" -o StrictHostKeyChecking=no %SSH_USER%@%SERVER_IP% "cd /home/deployuser && docker-compose down && sed -i 's/^BACKEND_VERSION=.*/BACKEND_VERSION=%VERSION%/' .env && docker-compose up -d"
                        '''
                    }
                }
            }
        }

    }
}
