/**
 * Types of functionality with Transaction entities
 */
export const SYNC_TRANSACTIONS_SUCCESS = "SYNC_TRANSACTIONS_SUCCESS";
export const SYNC_TRANSACTIONS_FAIL = "SYNC_TRANSACTIONS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const UPDATE_TRANSACTION_CATEGORY = "UPDATE_TRANSACTION_CATEGORY";
export const REMOVE_TRANSACTION_CATEGORY = "REMOVE_TRANSACTION_CATEGORY";
export const SET_LOADING = "SET_LOADING";
