/**
 * Types of functionality with Transaction entities
 */
export const SYNC_TRANSACTIONS_SUCCESS = "SYNC_TRANSACTIONS_SUCCESS";
export const SYNC_TRANSACTIONS_FAIL = "SYNC_TRANSACTIONS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const UPDATE_TRANSACTION_CATEGORY = "UPDATE_TRANSACTION_CATEGORY";
export const UPDATE_TRANSACTION_CATEGORY_FAILED =
   "UPDATE_TRANSACTION_CATEGORY_FAILED";
export const REMOVE_TRANSACTION_CATEGORY = "REMOVE_TRANSACTION_CATEGORY";
export const REMOVE_TRANSACTION_CATEGORY_FAILED =
   "REMOVE_TRANSACTION_CATEGORY_FAILED";
export const SET_LOADING = "SET_LOADING";
export const FETCH_TRANSACTIONS_SUCCESS = "FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_TRANSACTIONS_FAIL = "FETCH_TRANSACTIONS_FAIL";
export const SPLIT_TRANSACTIONS_SUCCESS = "SPLIT_TRANSACTIONS_SUCCESS";
export const SPLIT_TRANSACTIONS_FAILURE = "SPLIT_TRANSACTIONS_FAILURE";
export const ADD_TRANSACTION_SUCCESS = "ADD_TRANSACTION_SUCCESS";
export const ADD_TRANSACTION_FAILURE = "ADD_TRANSACTION_FAILURE";
export const REDUCE_TRANSACTION_SUCCESS = "REDUCE_TRANSACTION_SUCCESS";
export const REDUCE_TRANSACTION_FAILURE = "REDUCE_TRANSACTION_FAILURE";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAILURE = "DELETE_TRANSACTION_FAILURE";
