/**
 * File to store list of potential actions for our Incomes
 */
export const CREATE_INCOME_SUCCESS = "CREATE_INCOME_SUCCESS";
export const CREATE_INCOME_FAIL = "CREATE_INCOME_FAIL";
export const FETCH_INCOMES_SUCCESS = "FETCH_INCOMES_SUCCESS";
export const FETCH_INCOMES_FAIL = "FETCH_INCOMES_FAIL";
export const UPDATE_INCOME_SUCCESS = "UPDATE_INCOME_SUCCESS";
export const UPDATE_INCOME_FAIL = "UPDATE_INCOME_FAIL";
export const DELETE_INCOME_SUCCESS = "DELETE_INCOME_SUCCESS";
export const DELETE_INCOME_FAIL = "DELETE_INCOME_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_LOADING = "SET_LOADING";
