pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                checkout scmGit(branches: [[name: '*/feat/MoveFromGCloudToSelfHosting']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/KBavis/budgeting-app']])
            }
        }

        stage('Extract Version') {
            steps {
                script {
                    def packageJson = readJSON file: 'frontend/package.json'
                    def baseVersion = packageJson.version
                    def buildNumber = env.BUILD_NUMBER
                    env.VERSION = "${baseVersion}.${buildNumber}"
                    echo "Version: ${env.VERSION}"
                }
            }
        }

        stage('Build Frontend Docker Image') {
            steps {
                dir('frontend') {
                    script {
                        def version = env.VERSION
                        bat "docker build -t budget-app-frontend:${version} --build-arg VERSION=${version} -f docker/Dockerfile ."
                    }
                }
            }
        }

        stage('Push Frontend Docker Image to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'dockerhubpwd')]) {
                    script {
                        def version = env.VERSION
                        def dockerImage = "budget-app-frontend:${version}"
                        def dockerHubImage = "baviske/budget-app-frontend:${version}"
                        bat "docker login -u baviske -p ${dockerhubpwd} docker.io"
                        bat "docker tag ${dockerImage} ${dockerHubImage}"
                        bat "docker push ${dockerHubImage}"
                    }
                }
            }
        }

        stage('Deploy To Server') {
            steps {
                script {
                    withCredentials([
                        string(credentialsId: 'server-ip', variable: 'SERVER_IP'),
                        sshUserPrivateKey(credentialsId: 'deploy-ssh-key', keyFileVariable: 'SSH_KEY', usernameVariable: 'SSH_USER')
                    ]) {
                        bat '''
                            REM Fix SSH key permissions
                            icacls "%SSH_KEY%" /inheritance:r /grant "%USERNAME%:(R)"
                            
                            REM copy latest 
                            scp -i "%SSH_KEY%" -o StrictHostKeyChecking=no compose.yaml %SSH_USER%@%SERVER_IP%:/home/deployuser

                            REM ssh to update version and restart containers
                            ssh -i "%SSH_KEY%" -o StrictHostKeyChecking=no %SSH_USER%@%SERVER_IP% "cd /home/deployuser && docker-compose down && sed -i 's/^FRONTEND_VERSION=.*/FRONTEND_VERSION=%VERSION%/' .env && docker-compose up -d"
                        '''
                    }
                }
            }
        }
    }
}
