/**
 * File to store list of potential actions
 */
export const ACCOUNT_CREATED = "ACCOUNT_CREATED";
export const ACCOUNT_FAILED_CREATED = "ACCOUNT_FAILED_CREATED";
export const ACCOUNT_FAILED_DELETED = "ACCOUNT_FAILED_DELETED";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ACCOUNTS_FETCHED = "ACCOUNTS_FETCHED";
export const ACCOUNTS_FETCH_FAILED = "ACCOUNTS_FETCH_FAILED";
export const SET_LOADING = "SET_LOADING";
export const REMOVE_ACCOUNT_SUCCESS = "REMOVE_ACCOUNT_SUCCESS";
export const REMOVE_ACCOUNT_FAILURE = "REMOVE_ACCOUNT_FAILURE";
