export const ACCOUNT_CREATED = "ACCOUNT_CREATED";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const ACCOUNT_FAILED_CRATED = "ACCOUNT_FAILED_CREATED";
export const ACCOUNT_FAILED_DELETED = "ACCOUNT_FAILED_DELTED";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
