export const CONNECTION_CREATED = "CONNECTION_CREATED";
export const CONNECTION_FAILED = "CONNECTION_FAILED";
export const CONNECTION_DISCONNECTED = "CONNECTION_DISCONNECTED";
export const CONNECTION_CONNECTED = "CONNECTION_CONNECTED";
export const CONNECTION_PENDING = "CONNECTION_PENDING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
