/**
 * File to store potential actions for our CategoryTypes
 */
export const CREATE_CATEGORY_TYPES_SUCCESS = "CREATE_CATEGORY_TYPES_SUCCESS";
export const CREATE_CATEGORY_TYPES_FAIL = "CREATE_CATEGORY_TYPES_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const FETCH_CATEGORY_TYPES_SUCCCESS = "FETCH_CATEGORY_TYPES_SUCCESS";
export const FETCH_CATEGORY_TYPES_FAIL = "FETCH_CATEGORY_TYPES_FAIL";
export const UPDATE_CATEGORY_TYPE_SUCCESS = "UPDATE_CATEGORY_TYPE_SUCCESS";
export const UPDATE_CATEGORY_TYPE_FAIL = "UPDATE_CATEGORY_TYPE_FAIL";
export const SET_LOADING = "SET_LOADING";
