/**
 * Different Actions can occur regarding Authentication
 */
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_LOADING = "SET_LOADING";
export const FETCH_AUTH_USER_SUCCESS = "FETCH_AUTH_USER_SUCCESS";
export const FETCH_AUTH_USER_FAIL = "FETCH_AUTH_USER_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REFRESH_LINK_TOKEN_SUCCESS = "REFRESH_LINK_TOKEN_SUCCESS";
export const REFRESH_LINK_TOKEN_FAILURE = "REFRESH_LINK_TOKEN_FAILURE";
